services:
  db:
    image: postgres:18
    container_name: postgres_container
    restart: always
    volumes: 
      - ./docker/postgres:/var/lib/postgresql/18/docker
    ports:
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=admin

  cache:
    image: redis:8-alpine
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379

  db_testing:
    image: postgres:18
    container_name: postgres_testing_container
    restart: always
    volumes: 
      - ./docker/postgres:/var/lib/postgresql/18/docker
    ports:
      - 6544:5432
    environment:
      - POSTGRES_PASSWORD=admin